INSERT INTO cita (Fecha_Cita) VALUES
("2021-10-28 10:00:00"),
("2021-12-01 14:00:00"),
("2021-11-30 11:00:00"),
("2021-12-03 13:00:00"),
("2021-11-29 16:00:00"),
("2021-12-06 10:00:00"),
("2021-12-10 12:00:00"),
("2021-12-20 19:00:00"),
("2021-12-23 18:00:00"),
("2021-12-29 15:00:00"),
("2021-12-29 17:00:00"),
("2021-12-27 11:00:00"),
("2021-12-27 14:00:00"),
("2021-12-01 15:00:00"),
("2021-12-07 13:00:00"),
("2021-11-30 10:00:00"),
("2021-11-30 14:00:00"),
("2021-12-26 10:00:00"),
("2021-12-27 17:00:00"),
("2021-12-02 15:00:00");


INSERT INTO empleado (Nombre_Empleado, Apellido1_Empleado, Apellido2_Empleado, Telefono_Empleado, Cargo_Empleado, Especialidad, Correo_Empleado, Contraseña_Empleado, Horario_entrada_Empleado, Horario_salida_Empleado) 
VALUES
('Luis Angel', 'Aguilar', 'Ceja', '5534096789', 'Veterinario', 'Perros y Gatos', 'laacarguilarceja@gmail.com', 'luis123', "10:00", "17:00"),
('Cesar Sadrak','Martin','Moreno', '5567907860', 'Veterinario', 'Perros y Gatos', 'kreytos.pavi10@gmail.com', 'cesar123', "10:00", "17:00"),
('Emilio','Gallegos','Salinas', '5590123624', 'Veterinario', 'Reptiles', 'emilio_gallegos112@gmail.com','emilio123', "12:00", "20:00"),
('Victor Manuel','Cabello','Vargas', '5589453562', 'Finanzas', 'Ninguna', 'victor.cabello091@gmail.com','victor123', "11:00", "20:00"),
('Gabriela','Cruz','Gallegos','5551650291', 'Finanzas', 'Ninguna','ocbej@gmail.com', 'gabriela145', "11:00", "20:00"),
('Alejandra','Salto','Alfaro', '5555118636', 'Secretario', 'Ninguna', 'cnmlah@gmail.com', 'alejandra144', '10:00', "20:00" ),
('Sheyla','Romero','Monroy', '5555766516', 'Secretario', 'Ninguna', 'Ensjv@gmail.com', 'Sheyla123', "10:00", "20:00"),
('Marco','Duran','Romero', '5553560052', 'Veterinario', 'Reptiles', 'patosycorbatas@gmail.com', 'Marco123', "12:00", "20:00"),
('Patricia','Vargas','Arredondo', '5551000428', 'Veterinario', 'Aves', 'etesech99@gmail.com', 'Patricia123', "12:00", "20:00"),
('Anahi','Salinas','Hernandez', '5556727693', 'Veterinario', 'Aves', 'holacomoestas@gmail.com', 'Anahi123', "12:00", "20:00"),
('Brenda','Cisneros','Lopez', '5521630831', 'Veterinario', 'Mamíferos', 'BrenLopez@gmail.com', 'Brenda123', "12:00", "20:00"),
('Ivonne','Ugalde','Guerrero', '5553990664', 'Veterinario', 'Mamíferos', 'gue_rro98@outlook.com', 'ivon1123', "12:00", "20:00"),
('Maria','Sandoval','Martinez', '5576458792', 'Veterinario', 'Peces', 'marmar26@gmail.com', 'Maria123', "13:00", "20:00"),
('Ana','Zapata','Moreno', '5555144116', 'Gerente', 'Ninguna', 'bibvb@gmail.com', 'ana123', "10:00", "20:00"),
('Antonio','Ceja','Gonzalez', '5556733612', 'Veterinario', 'Ninguna', 'elpepe@gmail.com', 'Antonio123', "12:00", "19:00"),
('Karla','Benítez','Quiroz', '5555965229', 'Veterinario', 'Ninguna', 'quiroz_beni66@outlook.com', 'Karla123', "12:00", "19:00");

INSERT INTO mascota (Nombre_Mascota, Especie_Mascota) VALUES
('Cascabel', 'Perros'),
('Yubarto', 'Perros'),
('Chapi', 'Aves'),
('Barti', 'Aves'),
('Pequito', 'Perros'),
('Joyita', 'Perros'),
('Michi', 'Gatos'),
('Bigotes', 'Gatos'),
('Chonchis', 'Perros'),
('Nela', 'Reptiles'),
('Cheeto', 'Mamiferos'),
('Gary', 'Gatos'),
('Otto', 'Mamiferos'),
('Rocky', 'Perros'),
('Bali', 'Peces'),
('David', 'Aves'),
('Smile', 'Reptiles'),
('Brú', 'Peces'),
('Chester', 'Perros'),
('King', 'Gatos');

INSERT INTO sucursal(Nombre_Sucursal, Calle_Sucursal, Num_ext_Sucursal, Num_int_Sucursal, Colonia__Sucursal, Delegacion_Sucursal,
CP_Sucursal, Ciudad_Sucursal, Telefono) VALUES
('Patitas Felices Nápoles', 'Alabama', '178', '23', 'Nápoles', 'Benito Juárez', '03810', 'Ciudad de México', '5520934652'),
('Patitas Felices Coyoacan', 'Real de Los Reyes', '158', '30','Los Reyes', 'Coyoacán', '04330', 'Ciudad de México', '5589096755'),
('Patitas Felices Iztapalapa', 'Porvenir', '60', '05', 'Las Arboledas', 'Iztapalapa', '09790', 'Ciudad de México', '5545341290'),
('Patitas Felices Interlomas', 'Av. Secretaría de Marina', '700', '08', 'Lomas del Chamizal', 'Cuajimalpa de Morelos', '05129', 'Ciudad de México', '5511788909'),
('Patitas Felices Iztacalco', 'Añil', '144', '56', 'Granjas México', 'Iztacalco', '08400', 'Ciudad de México', '5526407810'),
('Patitas Felices Coapa', 'Manuela Cañizares', '112', '10', 'Coapa, Culhuacan', 'Coyoacán', '04480', 'Ciudad de México', '5580146989');

INSERT INTO ticket(Fecha, Cantidad) VALUES
("2021-10-28 10:55:00", '2'),
("2021-10-07 19:09:00", '1'),
("2021-09-11 16:04:00", '2'),
("2021-05-02 18:02:00", '2'),
("2021-06-22 01:50:00", '3'),
("2021-02-11 09:38:00", '2'),
("2021-11-10 14:28:00", '1'),
("2021-10-28 08:43:00", '2'), 
("2021-10-28 10:55:00", '2'),
("2021-10-03 02:09:00", '4'),
("2021-10-07 10:09:00", '2'),
("2021-10-03 09:10:00", '2'),
("2021-10-07 19:09:00", '1'),
("2021-10-02 07:20:00", '3'),
("2021-11-10 01:23:00", '2'),
("2021-11-01 01:20:00", '1'),
("2021-11-03 11:10:00", '3'),
("2021-02-11 17:56:00", '1'),
("2021-02-09 12:28:00", '2'),
("2021-02-10 13:10:00", '1'),
("2021-06-07 19:09:00", '2'),
("2021-04-06 10:02:00", '1'),
("2021-04-10 13:09:00", '1'),
("2021-05-11 10:10:00", '1'),
("2021-03-07 18:12:00", '1'),
("2021-04-05 12:10:00", '2'),
("2021-05-11 08:11:00", '2'),
("2021-03-12 21:15:00", '1'),
("2021-01-10 22:18:00", '1'),
("2021-03-09 23:00:00", '1');

INSERT INTO producto(Nombre_Producto, precio, Descripcion, Categoria, Especie, Imagen_Produc)VALUES
('Alimento para perros marca Poder Caning', '600.00', 'Alimento para perro  de 25 kg para adultos de razas grandes', 'Alimentos', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Alimento\Comida-para-perro-Poder-Canino-01.jpg'),
('Alimento para perros marca Ganador', '650.00', 'Alimento para perro de  20 kg para cachorros de razas pequeñas', 'Alimentos', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Alimento\Ganador.jpg'),
('Lata de alimento marca Pedigree', '30.00', 'Lata de trozos de res y queso 125g', 'Alimentos', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Alimento\Pedigree-1.jpg'),
('Lata de alimento marca Dog Chow', '25.00', 'Lata de trozos de cordero de  100g para adultos', 'Alimentos', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Alimento\dogchow.jpg'),
('Lata de alimento marca Dog Chow', '25.00', 'Lata de trozos de pavo 100g para adultos', 'Alimentos', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Alimento\DOG-CHOW-ADULTO.jpg'),
('Alimento para perros marca Nupec', '690.00', 'Alimento para perro  de 8 kg para cachorros', 'Alimentos', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Alimento\Nupec_Cachorro.jpg'),
('Cama para perro', 238.42, 'Cama para perro redonda color crema', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\Cama redonda.jpg'),
('Cama rosada para perro', 249.3, 'Cama rosa para perro con peluche', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidadoa\cama rosa.jpg'),
('Cama rectangular azul', 327.86, 'Cama rectangular color azul para perro grande', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\cama azul.jpg'),
('Shampoo para perro antipulgas', 61.59, 'Shampoo de perro antipulgas marca ppt con olor a chicle', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\shampoo1.jpg'),
('Cepillo para perro', 64.46, 'Cepillo para perros removedor de pelo y suciedad', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\cepillo1.jpg'),
('Collares para Perro', 166.63, 'Set de collar para perro con correa color azul', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\set-collar-correa.jpeg'),
('Collar para Perro', 66.63, 'Collar para perro color rosal', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\collar2.jpeg'),
('Shampoo para perros antimicotico', 66.29, 'Shampoo para perros marca Hartz anntipulgas', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\shampoo2.jpg'),
('Cepillo para perros Trixie', 89.26, 'Cepillo para perros de cabello rizado y largo', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\cepillo2.jpg'),
('Paquete de cepillos de dientes', 213.79, 'Dos cepillos de dientes de marca Boshel cerdas suaves', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\cepillo_dientes.jpg'),
('Cepillo de dientes Virbac', 93.13, 'Cepillo de dientes de doble punta morado', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\cepillo_dientes2.jpg'),
('Pasta y cepillo marca Pets', 127.77, 'Paquete de pasta y cepillo de dientes para perros', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\pasta_cepillo.jpg'),
('Juguete chillon para perro', 47.06, 'Juguete chillon de halloween', 'Juguetes', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Juguetes\Juguete-Halloween.jpg'),
('Modedera para perro', 33.08, 'Mordedera para perro con pelota', 'Juguetes', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Juguetes\mordedera.jpeg'),
('Jueguete chillon para perro ', 45.45, 'Juguete para perro en forma de pierna de pollo', 'Juguetes', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Juguetes\juguete_pollo.jpg'),
('Sueter para perros talla mediana', 106.6, 'Sueter para perro de copos de nieve azul', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\sueter1.jpg'),
('Vestido para perros', 96.31, 'Vestido con moño rojo', 'Cuidados', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Cuidados\sueter2.jpg'),
('Pet Craft Supply Juego de Juguetes de Peluche', 272.76, 'Paquete de juguetes de peluche para perro en forma de taco y aguacate', 'Juguetes', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Juguetes\aguacate.jpg'),
('ZippyPaws-Juguete de Peluche NomNomz', 256.16, 'ZippyPaws - Juguete de Peluche para Perro con chirriador de Peluche-Taco', 'Juguetes', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Juguetes\taco.jpg'),
('ZippyPaws Juguetes interactivos para perros', 156.74, 'Juguetes para perros chirriantes forma de maceta de miel', 'Juguetes', 'Perros', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Perros\Juguetes\abejas.jpg'),
('Alimento Minino para gato', 606.03, 'Alimento Minino para gato sabor pollo/pescado en bolsa de 15kg', 'Alimentos', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Alimento\alimento1.jpg'),
('Alimento Minino Plus para gato', 693.23, 'Alimento Minino Plus para gato adulto sabor carne/pollo/pavo en bolsa de 10kg', 'Alimentos', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Alimento\alimento2.jpg'),
('Royal Canin Croquetas para Gatos, Spayed', 619.01, 'Royal Canin Croquetas para Gatos, Spayed Neutered Appetite Control, 2.72 kg', 'Alimentos', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Alimento\alimento3.jpg'),
('Comida húmeda para gatos', 35.91, 'Comida húmeda para gatos de atún y caballa lata de 3 onzas', 'Alimentos', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Alimento\lata1.jpg'),
('Whiskas comida para gatos', 33.16, 'Alimento húmedo formulado para la nutrición de gatitos en crecimiento', 'Alimentos', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Alimento\lata2.jpg'),
('Felix Alimento Húmedo', 34.22, 'Felix Alimento Húmedo Sabor Filetes de Salmón en Salsa lata de 156g', 'Alimentos', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Alimento\lata3.jpg'),
('Collar para gatito con cascabel', 246.2, '2 unidades, hebilla de seguridad,diseño clásico a cuadros, ajustable de 15 a 20 cm', 'Cuidados', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Cuidados\collar_gato1.jpg'),
('Collares de gato de Navidad a cuadros', 286.72, 'Paquete de 2 collares de gato de Navidad a cuadros, ajustables', 'Cuidados', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Cuidados\collar_gato2.jpg'),
('Poste rascador para gatos', 673.46, 'Poste rascador para gatos y gatitos, diseño de palmera de coco', 'Cuidados', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Cuidados\cama1.jpg'),
('Caja de arena para gatos Dymoll', 237.44, 'Caja de arena plegable con entrada superior cubierta', 'Cuidados', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Cuidados\caja arena.jpg'),
('Shampoo Natural para Pelo Largo Gato', 195.23, 'Espree Shampoo Natural para Pelo Largo para Gato, 354 ml', 'Cuidados', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Cuidados\shampooG.jpg'),
('Colonia con Aroma a Talco para Perro y Gato', 149.13, 'Tropiclean Colonia con Aroma a Talco para Perro y Gato', 'Cuidados', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Cuidados\coloniaG.jpg'),
('Varita Flexible con Pluma para Gato', 148.15, 'Leaps & Bounds Thrill and Chase Varita Flexible con Pluma, Naranja', 'Cuidados', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Juguetes\pluma1.jpg'),
('Araña Saltarina para Gato', 93.19, 'Leaps & Bounds Thrill and Chase Araña Saltarina, Azul', 'Juguetes', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Juguetes\araña.jpg'),
('Juguete para Gato Fancy Pets', 64.84, 'Paquete de dos ratoncitos de tela para gato', 'Juguetes', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Juguetes\ratones.jpg'),
('Bolitas de tela para gato', 56.52, 'Bolitas de tela para gato con rayas', 'Juguetes', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Juguetes\bolitas.jpg'),
('Mapache Kicker para Gato', 157.01, 'Leaps & Bounds Mapache Kicker para Gato, Gris', 'Juguetes', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Juguetes\mapache.jpg'),
('Pelota de Terciopelo', 19.02, 'Leaps & Bounds Pelota de Terciopelo', 'Juguetes', 'Gatos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Gatos\Juguetes\pelotas.jpg'),
('Mazuri para Aves Grandes', 99.19, 'Alimento de Mantenimiento 650 Grs', 'Alimentos', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Aliment\alimentoAve.jpg'),
('Mezcla de Semillas', 108.34, 'Mezcla de Semillas p/Loritos y Ninfas 500g Red Kite', 'Alimentos', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Alimento\alimentoCanario.jpg'),
('Mezcla p/Aves Silvestres', 121.59, 'Mezcla p/Aves Silvestres y del Hogar 900g Red Kite', 'Alimentos', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Alimento\alimentoSilv.jpg'),
('Mezcla de Semillas p/Loros y Cacatuas', 127.11, 'Mezcla de Semillas p/Loros y Cacatuas 500g Red Kite', 'Alimentos', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Alimento\alimentoloro.jpg'),
('Jaula para Pájaros Jaula de Aves Canarios', 608.22, 'Yaheetech Jaula para Pájaros Jaula de Aves Canarios', 'Cuidados', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Cuidados\jaulaCanario.jpg'),
('Jaula para Pájaros grandes', 617.93, 'Yaheetech Jaula para Pájaros Jaula con Comedero 40 x 40 x 58 cm', 'Cuidados', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Cuidados\jaulaLoro.jpg'),
('Bañera para Ave con Espejo', 50.91, 'You & Me Bañera para Ave con Espejo', 'Cuidados', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Cuidados\bañera.jpg'),
('Bañera redonda para ave', 43.73, 'Lixit Bañera de Fácil Instalación, 12 cm Diámetro', 'Cuidados', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Cuidados\bañeraRedonda.jpg'),
('Bebedero Tipo Silo', 106.91, 'JW Pet Company Bebedero Tipo Silo, Grande 24.13 cm Largo', 'Cuidados', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Cuidados\bebedero.jpg'),
('Comedero con Gancho para Ave', 46.87, 'You & Me Comedero con Gancho para Ave', 'Cuidados', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Cuidados\comedero.jpg'),
('Puente Colgante para Mascotas', 73.25, 'Naroote Puente Colgante para Mascotas, Suministro para Jugar', 'Juguetes', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Juguetes\puente.jpg'),
('Columpio para aves', 61.32, 'Columpio para aves de madera juguete madera loro', 'Juguetes', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Juguetes\columpio.jpg'),
('Juguete de Palo de pie para pájaros', 295.72, 'Juguete de Percha de Jaula de pájaros Estable', 'Juguetes', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Juguetes\juguetePie.jpg'),
('Cadena de Pelotas con Campana', 56.57, 'JW Pet Company Cadena de Pelotas con Campana', 'Juguetes', 'Aves', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Aves\Juguetes\jugueteCampana.jpg'),
('Alimento en Hojuelas para Peces', 125.63, 'Tetra Min Alimento en Hojuelas para Peces Tropicales, 100 g', 'Alimentos', 'Peces', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Peces\Alimento\tropicalPeces.jpg'),
('Alimento para pez dorado', 108.37, 'Alimento para pez dorado', 'Alimentos', 'Peces', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Peces\Alimento\alimentoPezDor.jpg'),
('Pruebas para Acuario', 342.33, 'Tetra Easy Strips Pruebas 6 en 1 para Acuario, 25 Reactivos', 'Cuidados', 'Peces', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Peces\Cuidados\Acuario.jpg'),
('Acondicionador para Acuario', 106.89, 'Tetra Aqua Safe Acondicionador para Acuario, 250 ml', 'Cuidados', 'Peces', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Peces\Cuidados\acondicionador.jpg'),
('Plantas Glofish', 153.71, 'Tetra Plantas Glofish Surtido Paq', 'Cuidados', 'Peces', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Peces\Cuidados\plantitas.jpg'),
('Alimento para reptiles acuaticos', 42.55, 'Alimento para reptiles acuaticos Wardley', 'Alimentos', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Alimento\tortugasAlim.jpg'),
('Suplemento de calcio', 108.73, 'Repashy superalimentos Calcio Plus 85g reptil Suplemento de calcio', 'Alimentos', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Alimento\AlimentoSerp.jpg'),
('Alimento Para Pequeños Reptiles', 143.8, 'Mazuri Alimento Para Pequeños Reptiles 450g', 'Alimentos', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Alimento\alimPeque.jpg'),
('Lámpara Calefactora para Terrario', 1194.22, 'Zoo Med Powersun UV Lámpara Calefactora para Terrario, 100 Watts', 'Cuidados', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Cuidados\lamparita.jpg'),
('Foco Tropical Uvb', 1050.77, 'Zoo Med Paquete de Foco Tropical Uvb 5.0 & Lámpara Calefactora, 60 Watts', 'Cuidados', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Cuidados\foco.jpg'),
('Bombilla Luz de Luna', 286.41, 'Zoo Med Moonlite Bombilla Luz de Luna para Reptiles, 60 Watts', 'Cuidados', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Cuidados\uv.jpg'),
('Puente Flotante para Tortuga', 347.35, 'Zoo Med Puente Flotante para Tortuga Acuática, Grande', 'Juguetes', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Juguetes\puente.jpg'),
('Escondite Reversible', 173.66, 'Escondite Reversible, 20.3 cmx16.5 cmx 8.8 cm ', 'Juguetes', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Juguetes\escondite.jpg'),
('Cueva Escondite', 73.38, 'Yolcame Cueva Escondite Mediana Color Natural para Reptiles', 'Juguetes', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Juguetes\cueva.jpg'),
('Bebedero para Reptil', 98.19, 'Zoo Med Repti Rock Bebedero para Reptil, X-Chico', 'Juguetes', 'Reptiles', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Reptiles\Juguetes\bebedero.jpg'),
('Mezcla de Heno Pasto', 333.78, 'Oxbow Mezcla de Heno Pasto Timothy y Pasto de Orchard para Roedores ', 'Alimentos', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Alimento\pasto.jpg'),
('Heno Timothy', 352.98, 'Oxbow Heno Timothy, 2.5 kg', 'Alimentos', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Alimento\heno.jpg'),
('Snack de Malta', 94.1, 'Cunipic Alpha Pro Snack de Malta, 50 g', 'Alimentos', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Alimento\snack.jpg'),
('Premio para Roedores', 129.05, 'Versele Laga Complete Crock Premio para Roedores Sabor a Hierbas, 50 g', 'Alimentos', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Alimento\premio.jpg'),
('Premios Sabor Fresa para Roedores', 119.55, 'Oxbow Simple Rewards Premios Sabor Fresa para Roedores, 14 g', 'Alimentos', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Alimento\premio2.jpg'),
('Suplemento Digestivo para Roedores', 204.92, 'Oxbow Natural Science Suplemento Digestivo para Roedores, 120 g', 'Alimentos', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Alimento\suplemento.jpg'),
('Bebedero Estampado', 107.42, 'You & Me Bebedero Estampado de Puntos para Roedor, 254 ml', 'Cuidados', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Cuidados\bebederoRoe.jpg'),
('Shampoo en Seco', 128.19, 'Kaytee Quick & Clean Shampoo en Seco, 235 ml', 'Cuidados', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Cuidados\shampooseco.jpg'),
('Removedor de Olores', 247.53, 'Marshall Líquido Removedor de Olores de Hurones y Pequeñas Mascotas, 237 ml', 'Cuidados', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Cuidados\removedor.jpg'),
('Arnés y Correa Elástica', 202.0, 'Kaytee Arnés y Correa Elástica, Mediano', 'Juguetes', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Juguetes\correa.jpg'),
('Rueda Silent Spiner', 376.64, 'Kaytee Rueda Silent Spiner, 27 cm Diámetro', 'Juguetes', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Juguetes\ruedita.jpg'),
('Túnel Colgante', 228.36, 'Kaytee Túnel Colgante, 13.97 cm Largo x 17.78 cm Ancho', 'Juguetes', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Juguetes\tunel.jpg'),
('Casa para Baño', 265.74, 'Kaytee Casa para Baño, 21.59 cm x 21.59 cm x 21.59 cm', 'Juguetes', 'Mamiferos', 'C:\Users\laura\OneDrive\Documentos\Proyecto Ingenieria\Imagenes de productos\Mamiferos\Juguetes\casita.jpg');

INSERT INTO usuario(Nombre_Usuario, Apellido1_Usuario, Apellido2_Usuario, Correo_Usuario, Password_Usuario, Calle_Usuario, Num_ext_Usuario, Num_int_Usuario, 
Delegacion_Usuario, Ciudad_Usuario, CP_Usuario, Metodo_Pago, Num_Tarjeta, Telefono_Usuario)VALUES
('Manuel','Jaramillo','Wayne','shbj@gmail.com','Manuel123', 'Industrial Vallejo', '34', '2', 'Iztapalapa', 'Ciudad de México', '09870', 'Credito','4657890861238341','5555876524'),
('Juan','Renteria','Rodriguez','dbdu3b8@gmail.com','Juan123', 'Cleveland', '39', '9', 'Coyoacan', 'Ciudad de México', '08770', 'Debito','4645890354719383','5553560052'),
('Jose','Mendez','Quiroz','dbbb@gmail.com','Victor123', 'Marina Nacional', '70', '65', 'Cuauhtemoc', 'Ciudad de México', '08770', 'Credito','4612348907453121','5555786516'),
('Roberto','Bazaldua','Zapata','w0wes@gmail.com','Roberto123', 'Constituyentes', '56', '5', 'Miguel Hidalgo', 'Ciudad de México', '05690', 'Credito','4612348907453121','5555786516'),
('Dexter', 'Newis', 'Woolager', 'dwoolager0@home.pl', 'kcVaneUZ', 'Johnson', '084', '1', 'New York', 'Buffalo', '14205', 'Paypal', '5100141681443297', '7161499103'),
('Gayelord', 'Pietsma', 'Narducci', 'gnarducci1@stanford.edu', 'acuf4tfnAKbF', 'Judy', '21', '3', 'Alabama', 'Anniston', '36205', 'Paypal', '5100174300217040', '2564866968'),
('Hieronymus', 'Lansdowne', 'Cattach', 'hcattach2@disqus.com', 'aZociI', 'Pawling', '47', '29', 'Arizona', 'Phoenix', '85040', 'Credito', '5100177121491850', '4801768667'),
('Stephenie', 'Weerdenburg', 'McSkin', 'smcskin3@squarespace.com', 'S7RnaM', 'Westerfield', '4', '79', 'Nebraska', 'Lincoln', '68505', 'Debito', '5100138380526711', '4023165678'),
('Winona', 'Wapol', 'Sneyd', 'wsneyd4@princeton.edu', 'a57gjfJUjo6', 'Surrey', '35465', '42478', 'Texas', 'Gatesville', '76598', 'Credito', '5100133988660558', '2544322240'),
('Mariellen', 'Naris', 'Gentzsch', 'mgentzsch5@goodreads.com', 'Vft91k', 'Glacier Hill', '4', '95427', 'Pennsylvania', 'Pittsburgh', '15230', 'Debito', '5100142914511181', '4126137349'),
('Stanton', 'Prosh', 'Ryce', 'sryce6@mail.ru', 'RUgfS2', 'Weeping Birch', '08', '79003', 'Georgia', 'Atlanta', '31196', 'Credito', '5100178319210037', '4041763676'),
('Huey', 'Bastable', 'Algie', 'halgie7@jugem.jp', '39Ovv8xynA', 'Bultman', '440', '89721', 'Texas', 'El Paso', '79994', 'Debito', '5100173212343704', '9151466201'),
('Saunders', 'Cockroft', 'Jiras', 'sjiras8@slashdot.org', 'AQmbmcopdy', 'Bellgrove', '5824', '0832', 'Kentucky', 'Louisville', '40210', 'Paypal', '5100130772031707', '5029064368'),
('Papagena', 'Geertsen', 'Schulze', 'pschulze9@spiegel.de', 'Bnm2Bk638Z', 'Boyd', '4', '9191', 'Arizona', 'Peoria', '85383', 'Paypal', '5100131678191520', '6231625901'),
('Benni', 'O''Mannion', 'Adriani', 'badriania@bloglines.com', 'Yeaxh3r', 'Kennedy', '4904', '71', 'Tennessee', 'Nashville', '37215', 'Paypal', '5100141922034574', '6154741650'),
('Shaylyn', 'Heeron', 'Camerana', 'scameranab@dyndns.org', 'uNgxjwipyv', 'Moland', '4', '792', 'Florida', 'Fort Lauderdale', '33320', 'Credito', '5100131142377556', '7549658546'),
('Nollie', 'Emblen', 'Gaukroger', 'ngaukrogerc@devhub.com', 'IPgMWsIs93', 'Anthes', '356', '59', 'Texas', 'Houston', '77060', 'Debito', '5100145134487371', '8322230282'),
('Erinn', 'Davley', 'Eastway', 'eeastwayd@yelp.com', 'pYVLWYgQd', 'Waubesa', '6985', '25146', 'Virginia', 'Roanoke', '24009', 'Credito', '5100174091916677', '5405868071'),
('Lilia', 'Bister', 'Martignoni', 'lmartignonie@amazon.co.jp', 'JVqrVOHtkh5', 'Prairieview', '1', '2', 'Georgia', 'Savannah', '31416', 'Debito', '5100147186867658', '9126788072'),
('Ewart', 'Kezar', 'Dyment', 'edymentf@plala.or.jp', 'WkOAt4quNXY', 'Annamark', '80', '5743', 'Oregon', 'Portland', '97206', 'Debito', '5100145794587270', '5039735002'),
('Gaby', 'Roman', 'Durrand', 'gdurrandg@mail.ru', 'YxCMdizb', 'Wayridge', '335', '9', 'Georgia', 'Atlanta', '30380', 'Credito', '5100171513377132', '4047318615'),
('Dalston', 'Dearing', 'McKirdy', 'dmckirdyh@tmall.com', 'sdh6D68Y', 'Forster', '26873', '262', 'Texas', 'Austin', '78726', 'Paypal', '5100147082020444', '5129437189'),
('Chucho', 'Peaple', 'Borles', 'cborlesi@dropbox.com', 'B4DjgxXVAPh', 'Fordem', '05', '68', 'Nebraska', 'Omaha', '68197', 'Credito', '5100175503915637', '4025447553'),
('Karna', 'Straker', 'Cocci', 'kcoccij@constantcontact.com', '53LZC3Xnh', 'Goodland', '3788', '8', 'South Carolina', 'Columbia', '29208', 'Debito', '5100134252680371', '8036955557');

insert into expediente (id_sucursal, id_mascota, id_cita) values 
(5, 11, 4),
(6, 2, 8),
(2, 17, 17),
(5, 7, 18),
(5, 20, 12),
(6, 17, 10),
(6, 16, 1),
(2, 20, 12),
(6, 16, 9),
(2, 3, 17),
(6, 11, 7),
(4, 6, 3),
(3, 1, 18),
(1, 14, 8),
(4, 15, 20),
(1, 19, 11),
(6, 10, 20),
(1, 13, 3),
(6, 17, 10),
(5, 15, 9),
(2, 6, 4),
(3, 16, 6),
(3, 3, 10),
(2, 20, 17),
(2, 6, 2);

	


select * FROM cita;
select * FROM empleado;
select * from mascota;
select * from sucursal;
select * from ticket;
select * from producto;
select * from usuario;
select * from expediente;

delete from cita;
delete from empleado;
delete from mascota;
delete from sucursal;
delete from ticket;
delete from producto;







